name: OOB Testing Pipeline
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install imageio pytest pytest-cov
        
      - name: Run Functional & Performance Tests
      
        run: |
          pytest tests/ --cov=imageio --cov-report=xml:coverage.xml --junitxml=results.xml
        continue-on-error: false

      - name: Generate MD Report
        if: always()
        run: python scripts/report_generator.py

      - name: Publish Summary to GitHub UI
        if: always()
        run: |
          if [ -f raport.md ]; then
            cat raport.md >> $GITHUB_STEP_SUMMARY
          else
            echo "## Błąd: Plik raport.md nie został wygenerowany!" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Archive Test Artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: testing-outputs
          path: |
            raport.md
            coverage.xml
            results.xml
          retention-days: 7
